FROM docker:20.10.24

# Install required packages
RUN apk add --no-cache python3 py3-pip \
    && apk add --no-cache build-base \
    && apk add --no-cache postgresql-client \
    && apk add --no-cache docker-cli \
    && apk add --no-cache curl \
    && apk add --no-cache git \
    && apk add --no-cache make \
    && apk add --no-cache libffi-dev \
    && apk add --no-cache openssl-dev \
    && apk add --no-cache wget \
    && apk add --no-cache bash \
    && apk add --no-cache jq

# Install Docker Compose
RUN curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose

# Create and activate a virtual environment for Python packages
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Install AWS CLI and other Python packages inside the virtual environment
RUN pip install --upgrade pip \
    && pip install awscli \
    && pip install virtualenv \
    && pip install yasha

# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x kubectl \
    && mv kubectl /usr/local/bin/

# Set environment variables
ENV LANG=C.UTF-8 \
    PATH="/usr/local/bin:${PATH}"

CMD ["bash"]
